Implemented Linux export redirection

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -33,7 +33,8 @@ jobs:
           cmake ${{ github.workspace }}/CMakeLists.txt -DCMAKE_TOOLCHAIN_FILE="tests/toolchains/linux_i386.toolchain" -DCMAKE_BUILD_TYPE=Debug -DMINIDETOUR_BUILD_TESTS=ON -S . -B build
           cmake --build build
           #find build
-          build/tests
+          cd ${{ github.workspace }}/build
+          ./tests
 
       - name: Linux tests gcc (x64)
         if: ${{ matrix.os == 'ubuntu-latest' && matrix.platform == 'x64' }}
@@ -52,11 +53,14 @@ jobs:
           cmake --build build/linux_x64
           
           echo "### Running ARM tests ###"
-          qemu-arm -L /usr/arm-linux-gnueabi build/linux_arm/tests || echo "Failed"
+          cd ${{ github.workspace }}/build/linux_arm/
+          qemu-arm -L /usr/arm-linux-gnueabi ./tests || echo "Failed"
           echo "### Running AARCH64 tests ###"
-          qemu-aarch64 -L /usr/aarch64-linux-gnu build/linux_aarch64/tests || echo "Failed"
+          cd ${{ github.workspace }}/build/linux_aarch64/
+          qemu-aarch64 -L /usr/aarch64-linux-gnu ./tests || echo "Failed"
           echo "### Running X64 tests ###"
-          build/linux_x64/tests
+          cd ${{ github.workspace }}/build/linux_x64/
+          ./tests
 
       - name: MacOS tests
         if: matrix.os == 'macos-latest'
@@ -65,8 +69,9 @@ jobs:
           cmake ${{ github.workspace }}/CMakeLists.txt -DCMAKE_BUILD_TYPE=Debug -DMINIDETOUR_BUILD_TESTS=ON -S . -B build
           cmake --build build
           #find build
-          build/macos_permission_fix builds/tests
-          build/tests
+          cd ${{ github.workspace }}/build
+          ./macos_permission_fix tests
+          ./tests
 
       - name: Windows tests (x32)
         if: ${{ matrix.os == 'windows-latest' && matrix.platform == 'x32' }}
@@ -75,7 +80,8 @@ jobs:
           cmake ${{ github.workspace }}\CMakeLists.txt -DCMAKE_BUILD_TYPE=Debug -DMINIDETOUR_BUILD_TESTS=ON -S . -B build -A Win32
           cmake --build build
           #Get-ChildItem -Recurse build
-          build\Debug\tests.exe
+          cd ${{ github.workspace }}\build\Debug
+          .\tests.exe
 
       - name: Windows tests (x64)
         if: ${{ matrix.os == 'windows-latest' && matrix.platform == 'x64' }}
@@ -84,4 +90,5 @@ jobs:
           cmake ${{ github.workspace }}\CMakeLists.txt -DCMAKE_BUILD_TYPE=Debug -DMINIDETOUR_BUILD_TESTS=ON -S . -B build -A x64
           cmake --build build
           #Get-ChildItem -Recurse build
-          build\Debug\tests.exe
+          cd ${{ github.workspace }}\build\Debug
+          .\tests.exe
